package com.TUBEDELIVERIES.Utility;

import java.io.Serializable;

public interface AppConstants extends Serializable {

    String LOGIN="login";
    String FORGET_PASS="reset-token";
    String MENU_DETAILS="list-menu";
    String SIGNUP="register";
    String USER_FAVORITE="user-favourite";
    String SAVE_CARD="card-save";
    String RESTRO_LIST="restorent-list";
    String RESTRO_DETAILS="detail-restorent/";
    String RESTRO_INFO="information-restorent/";
    String USER_PASSWORD="user-password";
    String ONGOING_ORDER="ongoing_order";
    String PREVIOUS_ORDER="previous_order";
    String SEARCH_RESTAURANT="search-restorent";
    String SOCIAL_MEDIA_LOGIN="socialmedialogin";
    String ADD_BALANCE_TOPUP="add-wallet";
    String ADDTOCART="add-to-cart";
    String CART_LISTING="cart-list";
    String DELETE_CARD="card-delete";
    String ADD_TO_CART_FROM_DB="add-to-cart-all";
    String OFFERS="offer";
    String BOOKDETAIL="bookdetails/";
    String TOP_RATED_RESTRO="top-rated-restorent";
    String FREE_COURSE_DETAIL="freecourse/";
    String SAVED_CARD_LISTING="card-list";
    String GETQUESTIONS="teststart";
    String GLOBAL_SEARCH="filterRestorentByDetails";
    String PLACE_ORDER="placeOrder";
    String NEAR_BY_RESTRO="near-by-restorent";
    String TOP_UP_HISTORY="topup-history";
    String CUISINES_LIST="cuisines-list";
    String CANCEL_ORDER="cancel_order";
    String REORDER="reorder";
    String MY_FORUM_VIDEO_ID="myforumvideo/";
    String Discussion_COMMENT_LIST="discussioncommentlist/";
    String TOP_UP_LIST="topup-list";
    String WALLET_AMOUNT="wallet-amount";
    String SAVED_CARD="card-list";
    String RATING_REVIEW="restorent-rating";
    String FILTER_RESTAURANT="filter-restorent";
    String SAVE_FAVOURITE="save-favourite";
    String VIEWPROFILE="viewprofile";
    String FORGOT_PASS="forgotpassword";
    String LIST_MENU_FILTER="list-menu-filter";
    String CHANGE_PASS = "changepassword";
    String LOGOUT = "logout";
    String DOUBT_SESSION  = "doubtsesion";
    String UPDATE_PROFILE = "user-update";
    String USER_DETAILS = "user-details";
    String BEFORE_SIGNUP_CHECK = "before-signup-check";
    String CART_DETAIL_SAVE = "card-detail-save";
    String UPCOMING_ORDER = "upcoming_order";
    String MY_NOTIFICATION = "myNotification";
    String STORIES = "stories";
    String SUBSCRIPTION_DETAILS = "subscription-detail";
    String ADD_SUBSCRIPTIONS = "add-subscription";
    String CENCEL_SUBSCRIPTION = "subscription-cancel";
    String CHECK_FUNDS = "check-funds";
    String NEAR_BY_GROCERY = "near-by-grocery";
    String FILTER_OPTION = "filter_options";
    String RESTRO_FILTER = "filter-restorent";
    String GET_MY_DETAILS = "json";
    String EXCHAGE_RATE = "latest";
    String GET_CURRENCY = "alpha/{code}";
    String GET_CURRENCY_SYMBOL = "currencymap.json";
    String CONFIRM_ORDER = "confirm_order";
    String APPLY_COUPON = "applycoupon";
}
